cooking_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='homepage'),
]

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('ajax/meta/type', views.meta_type_html, name='ajax_meta_type'),
    path('ajax/meta/data', views.meta_data_html, name='ajax_meta_data'),
    path('create/1', views.create, name='create'),
    path('create/2/recipe/<int:recipe_id>/', views.create_step2, name='create_step2'),
    path('edit/1/recipe/<int:recipe_id>/', views.edit, name='edit'),
    path('edit/2/recipe/<int:recipe_id>/', views.edit_step2, name='edit_step2'),
    path('delete/<int:recipe_id>/', views.delete, name='delete'),
    path('<int:recipe_id>', views.detail, name='detail'),
    path('<int:recipe_id>/comment', views.new_comment, name='comment'),
    path('<int:recipe_id>/score', views.vote_score, name='score'),
    path('search', views.full_search, name='search'),
]

recipes/models.py
from django.db import models
from datetime import datetime, timedelta
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


class Recipe(models.Model):
	name = models.CharField(max_length=100)
	time_preparation = models.IntegerField(default=1, validators=[MinValueValidator(1)])
	time_cooking = models.IntegerField(default=1, validators=[MinValueValidator(1)])
	time_rest = models.IntegerField(default=1, validators=[MinValueValidator(1)])
	cost = models.IntegerField(default=1, validators=[MinValueValidator(1)])
	steps = models.TextField()
	picture = models.ImageField(upload_to = 'pictures/', default = 'pictures/no-img.png')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	status = models.PositiveSmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	def was_published_recently(self):
		return self.created_at >= timezone.now() - timedelta(days=1)

	def is_enabled(self):
		return self.status == 1

	def __str__(self):
		return self.name

	def url(self):
		return "/recipes/" + str(self.id)

	def score_mean(self):
		scores = Score.objects.filter(recipe=self)
		if scores.count() == 0:
			return 0
		else:
			res = 0
			for score in scores:
				res += score.value

			return float(res/scores.count())


class MetaType(models.Model):
	type = models.CharField(max_length=100)
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name


class MetaData(models.Model):
	value = models.CharField(max_length=250)
	type = models.ForeignKey("MetaType", on_delete=models.PROTECT, related_name="meta_type")

	def __str__(self):
		return "[" + self.type.name + "] " + self.value


class RecipeMetaData(models.Model):
	recipe = models.ForeignKey("Recipe", on_delete=models.PROTECT, related_name="recipe")
	meta = models.ForeignKey("MetaData", on_delete=models.PROTECT, related_name="recipe_meta")

	def __str__(self):
		return "[" + self.recipe.name + "] " + self.meta.value


class Comment(models.Model):
	text = models.TextField()
	likes = models.IntegerField(default=0, validators=[MinValueValidator(0)])
	created_at = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
	recipe = models.ForeignKey("Recipe", on_delete=models.CASCADE)

	def __str__(self):
		return self.text


class Score(models.Model):
	value = models.IntegerField(default=0, validators=[MinValueValidator(0)])
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="author_score")
	recipe = models.ForeignKey("Recipe", on_delete=models.PROTECT, related_name="recipe_score")

	class Meta:
		unique_together = (("author", "recipe"),)

	def __str__(self):
		return str(self.value)

recipes/forms.py
from django.forms import ModelForm, Form, formset_factory
from django import forms
from recipes.models import Recipe, Comment, RecipeMetaData, MetaType, MetaData


class RecipeStep1Form(ModelForm):
	class Meta:
		model = Recipe
		fields = ['name', 'time_preparation', 'time_cooking', 'time_rest', 'cost', 'steps', 'picture']
		labels = {
			'name': 'Nom de votre recette',
			# 'ingredients': 'Liste des ingrédients nécessaires',
			'time_preparation': 'Temps de préparation',
			'time_cooking': 'Temps de cuisson',
			'time_rest': 'Temps de repos',
			'cost': 'Coût',
			'steps': 'Etapes de préparation',
			'picture': 'photo de votre plat',
		}
		help_texts = {
		 	'time_preparation': 'En minutes',
			'time_cooking': 'En minutes',
			'time_rest': 'En minutes',
			'cost': 'En euros',
		 	}
		required = {}


def load_select_type():
	tpl = (('', 'Choisissez une info'),)
	for i in range(300):
		tpl = tpl + ((str(i), ''),)
	return tpl


def load_value_type():
	tpl = (('', 'Choisissez une valeur'),)
	for i in range(300):
		tpl = tpl + ((str(i), ''),)
	return tpl


class RecipeStep2Form(Form):
	select_type = forms.ChoiceField(widget=forms.Select, choices=load_select_type())
	select_type.widget.attrs.update({'class': 'form-control'})
	select_type.widget.attrs.update({'required': 'required'})

	value_type = forms.ChoiceField(widget=forms.Select, choices=load_value_type())
	value_type.widget.attrs.update({'class': 'form-control'})
	value_type.widget.attrs.update({'required': 'required'})


RecipeStep2Formset = formset_factory(RecipeStep2Form, extra=1)


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['text']
		labels = {'text': 'Votre message'}

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.core.paginator import Paginator
from django.http import Http404, HttpResponse, HttpResponseForbidden
import recipes, core
from django.urls import reverse

from .forms import RecipeStep1Form, CommentForm, RecipeStep2Formset
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader

from recipes.models import Recipe, Comment, Score, RecipeMetaData, MetaType, MetaData


def index(request):
	recipes_list = Recipe.objects.filter(status=1)
	paginator = Paginator(recipes_list, 3)
	page = request.GET.get('page')

	recipes = paginator.get_page(page)

	return render(request, 'recipes/index.html', {'recipes': recipes})

@login_required
def delete(request, recipe_id):
	recipe = get_object_or_404(Recipe, id=recipe_id)

	if recipe.author != request.user:
		#return HttpResponseForbidden("Vous n'êtes pas autorisé à modifier cette recette")
		template = loader.get_template('error/403.html')
		return HttpResponseForbidden(
        template.render(request=request)
    )

	recipe.status = 0
	recipe.save()
	return redirect('recipes:index')
	


@login_required
def edit(request, recipe_id):
	recipe = get_object_or_404(Recipe, id=recipe_id)

	if recipe.author != request.user:
		#return HttpResponseForbidden("Vous n'êtes pas autorisé à modifier cette recette")
		template = loader.get_template('error/403.html')
		return HttpResponseForbidden(
        template.render(request=request)
    )

	if request.POST:
		form = RecipeStep1Form(request.POST, request.FILES, instance=recipe)
		if form.is_valid():
			recipe.save()
		return redirect('recipes:edit_step2', recipe.id)
	else:
		form = RecipeStep1Form(instance=recipe)
	return render(request, 'recipes/edit_step1.html', {'form': form, 'id': recipe_id})


@login_required
def edit_step2(request, recipe_id):
	recipe = get_object_or_404(Recipe, id=recipe_id)

	if request.POST:
		formset = RecipeStep2Formset(request.POST, instance=recipe)
		if form.is_valid():
			for form in formset:
				metadata = get_object_or_404(MetaData, pk=form.cleaned_data.get('value_type'))

				recipe_metadata = RecipeMetaData()
				recipe_metadata.meta = metadata
				recipe_metadata.recipe = recipe
				recipe_metadata.save()
			recipe.status = 1
			recipe.save()
			return redirect('recipes:index')
	else:
		formset = RecipeStep2Formset()
	return render(request, 'recipes/create_step2.html', {'formset': formset, 'recipe': recipe})

@login_required
def create(request):
	new_recipe = Recipe()
	if request.POST:
		form = RecipeStep1Form(request.POST, request.FILES)
		if form.is_valid():
			new_recipe.name = form.cleaned_data['name']
			new_recipe.time_preparation = form.cleaned_data['time_preparation']
			new_recipe.time_cooking = form.cleaned_data['time_cooking']
			new_recipe.time_rest = form.cleaned_data['time_rest']
			new_recipe.cost = form.cleaned_data['cost']
			new_recipe.steps = form.cleaned_data['steps']
			new_recipe.picture = form.cleaned_data['picture']
			new_recipe.author = request.user
			new_recipe.save()
		return redirect('recipes:create_step2', new_recipe.id)
	else:
		form = RecipeStep1Form
	return render(request, 'recipes/create_step1.html', {'form': form})


@login_required
def create_step2(request, recipe_id):
	print(recipe_id)
	recipe = get_object_or_404(Recipe, id=recipe_id)
	print(recipe.id)

	if request.POST:
		formset = RecipeStep2Formset(request.POST)

		if formset.is_valid():
			for form in formset:
				metadata = get_object_or_404(MetaData, pk=form.cleaned_data.get('value_type'))

				recipe_metadata = RecipeMetaData()
				recipe_metadata.meta = metadata
				recipe_metadata.recipe = recipe
				recipe_metadata.save()

			recipe.status = 1
			recipe.save()
			return redirect('recipes:index')
	else:
		formset = RecipeStep2Formset()

	return render(request, "recipes/create_step2.html", {'formset': formset, 'recipe': recipe})


def detail(request, recipe_id):
	recipe = get_object_or_404(Recipe, id=recipe_id)

	comments_list = Comment.objects.filter(recipe=recipe)
	paginator = Paginator(comments_list, 3)
	page = request.GET.get('page')

	comments = paginator.get_page(page)

	metas = RecipeMetaData.objects.filter(recipe=recipe)
	ingredients = []
	for meta in metas:
		if meta.meta.type.type == 'ingredient':
			ingredients.append(meta.meta)	
	form = CommentForm()
	if request.user.is_authenticated:
		score = Score.objects.filter(recipe_id=recipe_id, author=request.user).first()	
	else:
		score = 0
	score_mean = recipe.score_mean()

	if score:
		value = score.value
	else:
		value = 0

	return render(request, 'recipes/detail.html', {'recipe': recipe, 'comments': comments, 'score': value, 'score_mean': score_mean, 'form': form, 'ingredients': ingredients})


@login_required
def new_comment(request, recipe_id):
	if request.POST:
		form = CommentForm(request.POST)
		comment = Comment()
		if form.is_valid():
			comment.text = form.cleaned_data['text']
			comment.likes = 0
			comment.recipe = Recipe.objects.get(pk=recipe_id)
			comment.author = request.user
			comment.save()
			return redirect('recipes:detail', recipe_id)
	else:
		raise Http404("Not found")


@login_required
def vote_score(request, recipe_id):
	if request.POST:
		recipe = Recipe.objects.get(pk=recipe_id)
		value = request.POST["score"]
		score = Score.objects.filter(recipe=recipe, author=request.user).first()

		if score:
			score.value = value
		else:
			score = Score()
			score.value = value
			score.author = request.user
			score.recipe = recipe

		score.save()

		return HttpResponse("ok")
	else:
		raise Http404("Not found")


def meta_type_html(request):
	metas = MetaType.objects.all()
	return render(request, "recipes/ajax_select_meta_type.html", {"types": metas})


def meta_data_html(request):
	meta_type = get_object_or_404(MetaType, pk=request.GET.get("type_id"))
	metas = MetaData.objects.filter(type=meta_type)

	return render(request, "recipes/ajax_select_meta_data.html", {"data": metas})


def full_search(request):
	recipes = []
	if request.GET.get("key"):
		meta_data = MetaData.objects.filter(value__contains=request.GET.get("key")).values_list('id', flat=True)
		meta_data_recipe_ids = RecipeMetaData.objects.filter(meta__in=meta_data).values_list('recipe', flat=True)

		recipes = Recipe.objects.filter(name__contains=request.GET.get("key")) | Recipe.objects.filter(
			id__in=meta_data_recipe_ids)
	else:
		recipes = Recipe.objects.all()

	for recipe in recipes:
		metas = RecipeMetaData.objects.filter(recipe=recipe)
		ingredients = []
		for meta in metas:
			if meta.meta.type.type == 'ingredient':
				ingredients.append(meta.meta.value)
		recipe.ingredients = ingredients

	return render(request, "recipes/search.html", {"recipes": recipes})

recipes/templates/recipes/ajax_select_meta_data.html
<option value="">Choisissez une valeur</option>
{% for d in data %}
    <option value="{{ d.id }}">{{ d.value }}</option>
{% endfor %}

recipes/templates/recipes/ajax_select_meta_type.html
<option value="">Choisissez une info</option>
{% for type in types %}
    <option value="{{ type.id }}">{{ type.name }}</option>
{% endfor %}

recipes/templates/recipes/comment.html
{% load bootstrap4 %}
<h2>Note moyenne</h2>
{{ score_mean }}

<h2>Commentaires</h2>

<div class="pagination">
    <span class="step-links">
        {% if comments.has_previous %}
            <a href="?page=1">Première page</a>
            <span> - </span>
            <a style="font-size: 25px; font-weight: bold;" href="?page={{ comments.previous_page_number }}"><</a>
        {% endif %}

        <span class="current">
            Page {{ comments.number }} / {{ comments.paginator.num_pages }}
        </span>

        {% if comments.has_next %}
            <a style="font-size: 25px; font-weight: bold;" href="?page={{ comments.next_page_number }}">></a>
            <a href="?page={{ comments.paginator.num_pages }}">Dernière page</a>
        {% endif %}
    </span>
</div>

{% for comment in comments %}

    <div class="comment">
        <h3> {{ comment.author }} </h3>
        <p>{{ comment }}</p>
    </div>

{% empty %}
    <p>Soyez le premier à commenter cette recette !</p>
    {% if not user.is_authenticated %}
        <p><a href="{% url 'login' %}">Pour cela connectez vous ici</a></p>
    {% endif %}

{% endfor %}
{% if user.is_authenticated %}
<form action="{% url 'recipes:comment' recipe.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Valider le commentaire</button>
    {% endbuttons %}
</form>
{% endif %}

recipes/templates/recipes/create_step1.html
{% extends "core/base.html" %}
{% load bootstrap4 %}

{% block content %}

    <h1>Ajouter une recette</h1>
    <form action="{% url 'recipes:create' %}" method="post" style="height: 100%" enctype="multipart/form-data">
       {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Valider</button>
    {% endbuttons %}
    </form>
{% endblock %}

recipes/templates/recipes/create_step2.html
{% extends "core/base.html" %}
{% load bootstrap4 %}

{% block content %}



    <table class="table table-bordered" style="margin: 20px 0">
        <thead>
        <tr>
            <th colspan="2">Résumé de la recette <i>{{ recipe.name }}</i></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Temps de préparation</td>
            <td>{{ recipe.time_preparation }} minute(s)</td>
        </tr>
        <tr>
            <td>Temps de cuisson</td>
            <td>{{ recipe.time_cooking }} minute(s)</td>
        </tr>
        <tr>
            <td>Temps de repos</td>
            <td>{{ recipe.time_rest }} minute(s)</td>
        </tr>
        <tr>
            <td>Coût</td>
            <td>{{ recipe.cost }} €</td>
        </tr>
        <tr>
            <td>Les étapes</td>
            <td>{{ recipe.steps }}</td>
        </tr>

        </tbody>
    </table>


    <h2>Ajouter des informations complémentaires</h2>
    <p>Ces informations ne sont pas obligatoire mais permettent une meilleure visibilité de votre recette sur notre site</p>
    <form action="{% url 'recipes:create_step2' recipe.id %}" method="post" style="height: 100%">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="row form-row spacer">
                <div class="col-2 select-meta-type-cont">
                    {{form.select_type}}
                </div>
                <div class="col-4">
                    <div class="input-group select-meta-data-cont">
                        {{form.value_type}}
                        <div class="input-group-append">
                            <button class="btn btn-success add-form-row">+</button>
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}

        {% buttons %}
            <button type="submit" class="btn btn-primary">Valider</button>
        {% endbuttons %}
    </form>



    <script type='text/javascript'>
        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }
        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            var total = $('#id_' + prefix + '-TOTAL_FORMS').val();

            newElement.find('input').each(function() {
                var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            });

            newElement.find('select').each(function() {
                var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            });

            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            var conditionRow = $('.form-row:not(:last)');
            conditionRow.find('.btn.add-form-row')
                .removeClass('btn-success').addClass('btn-danger')
                .removeClass('add-form-row').addClass('remove-form-row')
                .html('<span class="glyphicon glyphicon-minus" aria-hidden="true">-</span>');
            return false;
        }
        function deleteForm(prefix, btn) {
            var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1){
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each(function() {
                        updateElementIndex(this, prefix, i);
                    });
                }
            }
            return false;
        }
        $(document).on('click', '.add-form-row', function(e){
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });
        $(document).on('click', '.remove-form-row', function(e){
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });

        $(document).ready(function () {
            $.get( "{% url 'recipes:ajax_meta_type' %}", function( data ) {
                $(".select-meta-type-cont select").html(data);
                $(".select-meta-data-cont select").prop('disabled', 'disabled');
            });

            $(".select-meta-type-cont select").change(function (e) {
                $.get( "{% url 'recipes:ajax_meta_data' %}", { type_id: $(this).val()}, function( data ) {
                    $(".select-meta-data-cont select").prop("disabled", false);
                    $(".select-meta-data-cont select").html(data);
                });
            })
        })
    </script>

{% endblock %}

recipes/templates/recipes/detail.html
{% extends "core/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="form-group">
            <div class=" col-sm-4 d-inline-block">
                    <h1>{{ recipe.name }}</h1>
            </div>
            <div class="col-sm-8 d-inline-block">
                {% if recipe.author == user %}
                    <a href="{% url 'recipes:edit' recipe.id %}" class="btn btn-primary">Modifier la recette</a>
                {% endif %}
            </div>
          </div>
    
    <img class="card-img-top"  alt="100%x180"
                 style="height: 180px; width: 180px; display: block; margin: auto"
                 src="/{{recipe.picture}} "
                 data-holder-rendered="true">
    <table class="table table-bordered" style="margin: 20px 0">
        <tbody>
        <tr>
            <td>Temps de préparation</td>
            <td>{{ recipe.time_preparation }} minute(s)</td>
        </tr>
        <tr>
            <td>Temps de cuisson</td>
            <td>{{ recipe.time_cooking }} minute(s)</td>
        </tr>
        <tr>
            <td>Temps de repos</td>
            <td>{{ recipe.time_rest }} minute(s)</td>
        </tr>
        <tr>
            <td>Coût</td>
            <td>{{ recipe.cost }} €</td>
        </tr>
        <tr>
            <td>Les étapes</td>
            <td>{{ recipe.steps }}</td>
        </tr>
        <tr>
            <td>Ingrédients</td>
            <td>
                <ul>
                    {% for ingredient in ingredients %}
                    <li>{{ingredient.value}}</li>
                {% endfor %}
                </ul>
            </td>
        </tr> 
        <tr>
            <td>Auteur</td>
            <td>{{ recipe.author }}</td>
        </tr> 
        </tbody>
    </table>

    {% if user.is_authenticated %}
        {% include "recipes/score.html" %}
    {% endif %}
    {% include "recipes/comment.html" %}

{% endblock %}

recipes/templates/recipes/edit_step1.html
{% extends "core/base.html" %}
{% load bootstrap4 %}

{% block content %}

    <h1>Modifier une recette</h1>
    <form action="{% url 'recipes:edit' id %}" method="post" style="height: 100%" enctype="multipart/form-data">
    <a href="{% url 'recipes:delete' id%}" class="btn btn-danger" onclick="return confirmAction()">Supprimer</a>
       {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Valider</button>
    {% endbuttons %}
    </form>

    <script>
    function confirmAction(){
        var confirmed = confirm("Voulez-vous vraiment supprimer cette recette ?");
        return confirmed;
    }
    </script>
{% endblock %}

recipes/templates/recipes/index.html
{% extends "core/base.html" %}
{% load bootstrap4 %}

{% block content %}

    <h1>Toutes les recettes</h1>

<div class="pagination">
    <span class="step-links">
        {% if recipes.has_previous %}
            <a href="?page=1">Première page</a>
            <span> - </span>
            <a style="font-size: 25px; font-weight: bold;" href="?page={{ recipes.previous_page_number }}"><</a>
        {% endif %}

        <span class="current">
            Page {{ recipes.number }} / {{ recipes.paginator.num_pages }}
        </span>

        {% if recipes.has_next %}
            <a style="font-size: 25px; font-weight: bold;" href="?page={{ recipes.next_page_number }}">></a>
            <a href="?page={{ recipes.paginator.num_pages }}">Dernière page</a>
        {% endif %}
    </span>
</div>
    <div class="cards">
    {% for recipe in recipes %}
        <div class="card" id="card{{ recipe.id  }}" style="width: 33%; display: inline-block; min-height: 400px; vertical-align: top; margin-bottom: 20px ">
            <img class="card-img-top"  alt="100%x180"
                 style="height: 180px; width: 180px; display: block; margin: auto"
                 src="/{{recipe.picture}} "
                 data-holder-rendered="true">
            <div class="card-body">
                <h5 class="card-title">{{ recipe.name }}</h5>
                <p class="card-text">
                    {{ recipe.steps|truncatechars:110 }}
                </p>
                <a href="{% url 'recipes:detail' recipe.id %}" class="btn btn-primary">Voir la recette</a>
                {% if recipe.author == user %}
                    <a href="{% url 'recipes:edit' recipe.id %}" class="btn btn-primary">Modifier la recette</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

recipes/templates/recipes/score.html
{% load bootstrap4 %}

<div>
    <h3>Notez cette recette : </h3>

    {% for i in "12345"|make_list %}

        <button class="star" star="{{ i }}">
            <i class="fas fa-star"></i>
        </button>
    {% endfor %}
</div>

<script>
    $(document).ready(function () {

        var star_value = {{ score }};

        $(".star").each(function () {
            if($(this).attr("star") <= {{ score }}){
                $(this).css("color", "Tomato")
            }
        });


        $('.star').hover(function () {
            var star = $(this).attr("star")
            $('.star').each(function (index) {
                if($(this).attr("star") <= star){
                    $(this).css("color", "Tomato")
                }
            })
        }, function () {
            $('.star').each(function (index) {
                if($(this).attr("star") > star_value) {
                    $(this).css("color", "#d9dadc")
                }
            })
        });

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');

        $('.star').click(function () {
            star_value = $(this).attr("star");

            $.post("{% url 'recipes:score' recipe.id %}", {score: $(this).attr("star"), "csrfmiddlewaretoken": csrftoken});
        });
    })
</script>

recipes/templates/recipes/search.html
{% extends "core/base.html" %}
{% load bootstrap4 %}

{% block content %}

    <table class="table table-bordered" style="margin: 20px 0">
        <thead>
        <tr>
            <th colspan="2">Résultats de la recherche</th>
        </tr>
        <tr>
            <th></th>
            <th>Nom</th>
            <th>Étapes</th>
            <th>Coût (€)</th>
            <th>Temps Total</th>
            <th>Ingrédients</th>
            <th>Lien</th>
        </tr>
        </thead>
        <tbody>
        {% for recipe in recipes %}
            <tr>
                <td> <img class="card-img-top"  alt="100%x180"
                          style="width: 70px; display: block; margin: auto"
                          src="/{{recipe.picture}} "
                          data-holder-rendered="true"></td>
                <td>{{ recipe.name }}</td>
                <td>{{ recipe.steps }}</td>
                <td>{{ recipe.cost }}</td>
                <td>{{ recipe.time_cooking }}</td>
                <td>
                    <ul>
                        {% for ingredient in recipe.ingredients %}
                            <li>
                                {{ ingredient }}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
                <td><a href="{{ recipe.url }}">Consulter la recette</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>



{% endblock %}