cooking_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('account/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='homepage'),
]

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('ajax/meta/type', views.meta_type_html, name='ajax_meta_type'),
    path('ajax/meta/data', views.meta_data_html, name='ajax_meta_data'),
    path('create/1', views.create, name='create'),
    path('create/2/recipe/<int:recipe_id>/', views.create_step2, name='create_step2'),
    path('edit/1/recipe/<int:recipe_id>/', views.edit, name='edit'),
    path('edit/2/recipe/<int:recipe_id>/', views.edit_step2, name='edit_step2'),
    path('delete/<int:recipe_id>/', views.delete, name='delete'),
    path('<int:recipe_id>', views.detail, name='detail'),
    path('<int:recipe_id>/comment', views.new_comment, name='comment'),
    path('<int:recipe_id>/score', views.vote_score, name='score'),
    path('search', views.full_search, name='search'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from recipes.models import Recipe


def index(request):
    recipes = Recipe.objects.filter(status=1).order_by('-created_at')[:3]
    return render(request, 'core/homepage.html', {'recipes': recipes})

core/templates/core/base.html
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{#{%  bootstrap_javascript jquery='full' %}#}

<!DOCTYPE html>
<html lang="fr">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>Cooking project</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Cooking Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage' %}">Accueil</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes:create' %}">Ajouter une recette</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Déconnexion</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Inscription</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Connexion</a>
                    </li>
                {% endif %}
            </ul>
            <form class="form-inline" action="{% url 'recipes:search' %}" style="margin-bottom: 0">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Nom ou autre caractéristique" name="key">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Chercher</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

core/templates/core/homepage.html
{% extends "core/base.html" %}
{% block title %}Home{% endblock %}
{% load static %}

{% block content %}
    <h1>Les dernières recettes</h1>
    <a href="{% url 'recipes:index' %}">Voir toutes les recettes...</a>

    <div class="cards">
    {% for recipe in recipes %}
        <div class="card" id="card{{ recipe.id  }}" style="width: 33%; display: inline-block; min-height: 400px; vertical-align: top; margin-bottom: 20px ">
            <img class="card-img-top"  alt="100%x180"
                 style="height: 180px; width: 180px; display: block; margin: auto"
                 src="/{{recipe.picture}} "
                 data-holder-rendered="true">
            <div class="card-body">
                <h5 class="card-title">{{ recipe.name }}</h5>
                <p class="card-text">
                    {{ recipe.steps|truncatechars:110 }}
                </p>
                <a href="{% url 'recipes:detail' recipe.id %}" class="btn btn-primary">Voir la recette</a>
                {% if recipe.author == user %}
                    <a href="{% url 'recipes:edit' recipe.id %}" class="btn btn-primary">Modifier la recette</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}